# Generated by Django 5.1 on 2024-08-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="read",
            new_name="is_read",
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="新訊息", max_length=225),
        ),
    ]
